import type { Metadata } from "next";
import "./globals.css";

import PageHeader from "@/components/PageHeader/PageHeader";
import Container from "@/components/Container/Container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="no">
      <body>
        <PageHeader />

        <main>
          <Container>
            {children}
          </Container>
        </main>
        
        <footer>
          <p>
            Copyright 2026
          </p>
        </footer>
      </body>
    </html>
  );
}
